### ISSUE TITLE
IHM - MesCreations

### ISSUE THREAD

**Issue by mh0** [Wiiz83/DoodleMe#17]
http://localhost:3000/api/events/createdBy/17(tous)

Mes événements à venir en attente de clôture
**http://localhost:3000/api/events/open/createdBy/17 (todo)**

Mes événements à venir cloturés
**http://localhost:3000/api/events/closed/createdBy/17 (todo)**

Mes événements passés
**http://localhost:3000/api/events/archived/createdBy/17 (todo)**

**Comment by Wiiz83** [comment]
Mes événements à venir en attente de clôture = Les événements **a clôturer** que j'ai créé

Mes événements à venir cloturés = Les événements clôturés (donc à venir) que j'ai créé

Mes événements passés = Les événements archivés que j'ai créé
