### ISSUE TITLE
IHM - Mes participations

### ISSUE THREAD

**Issue by mh0** [Wiiz83/DoodleMe#18]
http://localhost:3000/api/events/anweredBy/17 (tous)

Mes participations à venir
_http://localhost:3000/api/events/upcoming/closed/anweredBy/17 + dispo de l'utilisateur au créneau final  (todo)_
 
Mes participations en attente
_http://localhost:3000/api/events/upcoming/open/anweredBy/17 (todo)_

Mes participations passées
**http://localhost:3000/api/events/passed/anweredBy/17 +  (todo)**

**Comment by Wiiz83** [comment]
Mes participations à venir = Les événements **clôturés** que je n'ai pas créé et auquel je participe au créneau définitif (on n'affiche pas les événements où le créneau définitif est un créneau où j'ai répondu que je ne participais pas)

Mes participations passées = Les événements clôturés que je n'ai pas créé et auquel j'ai participé : **dateDuJour > DateCréneau**

**Comment by mh0** [comment]
![image](https://cloud.githubusercontent.com/assets/17098140/25999504/ae1bf960-3725-11e7-8923-edf05c71db03.png)
**participations à venir**
Du coup il va falloir afficher aussi les réponses aux events non clôturés
Tu peux donc   afficher tous les events à venir avec leur **date de cloture (ou N/D si ouvert)**

**Comment by Wiiz83** [comment]
Ah oui merde, donc changement de programme.

Mes participations à venir = Les événements clôturés que je n'ai pas créé et auquel j'ai donné un réponse. Il faut renvoyer la réponse de l'utilisateur par rapport au créneau définitif (Oui ou Non) histoire de l'afficher sur le tableau.

Mes participations en attente = Les événements non clôturés que je n'ai pas créé et auquel j'ai donné un réponse. Affichage de la réponse de l'utilisateur pour chaque créneau. = Pour modifier mes réponses 
(PAS LE TEMPS POUR L'INSTANT)

**Comment by Wiiz83** [comment]
Mes participations à venir ne fonctionne pas.
Mes participations archivés à faire.
