### ISSUE TITLE
Serveur - Contrôleur Events 

### ISSUE THREAD

**Issue by mh0** [Wiiz83/DoodleMe#2]
/events
- Opérations CRUD

/events/{idEvent}/recommandedCloseSlot
- Retourne l'id du créneau recommandé  

/events/{idEvent}/close/{SlotID}
- Cloture d'un évènement

/events/createdBy/{idUser}
- Evènements crées par un utilisateur

/events/anweredBy/{idUser}
- Evènements auxquels l'utilisateur a donné une réponse, triés par les plus récents

**Comment by imaneet** [comment]
Cloture d'évents, Events crées par 1 user et Evenements ou l'user a répondu sont fait (requête)
