### ISSUE TITLE
Blocage accès site si utilisateur non connecté 

### ISSUE THREAD

**Issue by Wiiz83** [Wiiz83/DoodleMe#22]
Si l'utilisateur n'est pas connecté, bloqué l'accès au site.

**Comment by mh0** [comment]
![image](https://cloud.githubusercontent.com/assets/17098140/26027854/ca861338-3815-11e7-9d5c-3fa9e7377262.png)
Toutes les requetes API sont bloquées et l'utilisateur n'a qu'une ihm vide

**Comment by mh0** [comment]
![image](https://cloud.githubusercontent.com/assets/17098140/26027863/03718efc-3816-11e7-93d8-7e77743e816a.png)

Il faudrait afficher un message d'erreur et / ou redireger l'utilisateur au login s'il n'est pas connecté (401 unauthorized)
